#!/bin/bash
mvn clean package dependency:copy-dependencies -DoutputDirectory=../FitNesseRoot/fitnesseJar/extlib  -DincludeScope=compile -Dmaven.test.skip=true
copy -f target/fitnesse-features.jar ../FitNesseRoot/fitnesseJar/extlib/